#!/usr/bin/env bash

root_dir=$PWD

cargo ndk --target arm64-v8a -o ./crates/notedeck_chrome/android/app/src/main/jniLibs/ build --profile release

cd ./crates/notedeck_chrome/android

./gradlew assembleDebug --no-daemon && adb install --user 0 -r app/build/outputs/apk/debug/app-debug.apk

cd $root_dir